/**
 * search · application · StrategyVersionMapper
 *
 * Resolves runtime strategy ids to database StrategyVersion UUIDs.
 *
 * Architecture (DB-key vs runtime-ref):
 *
 *   SearchCandidate
 *       │
 *       ├── BASE:  strategyId = "strategy.ma"          ← stable implementationRef
 *       │            ↓
 *       │         StrategyVersion (lookup by implementationRef)
 *       │            ↓
 *       │         strategyVersionId (UUID)            ← DB primary key
 *       │
 *       └── COMPOSITE: config.id = "strategy.composite.domain_guided.0_0"  ← stable implementationRef
 *                        ↓
 *                     StrategyVersion (lookup by implementationRef = config.id)
 *                        ↓
 *                     compositeVersionId (UUID)        ← DB primary key
 *                        ↓
 *                     For each component, look up the underlying StrategyVersion
 *                     by its implementationRef and write a CompositeComponent row.
 *
 * The mapper lives in the application layer — it touches Prisma directly.
 *
 * IMPORTANT INVARIANT:
 *   - The runtime identifier (`Strategy.id`, `StrategyVersion.implementationRef`)
 *     is a STABLE STRING like "strategy.ma" or "strategy.composite.domain_guided.0_0".
 *   - The DB primary keys (`StrategyDefinition.id`, `StrategyVersion.id`,
 *     `CompositeComponent.*`) are always UUIDs and managed by Prisma.
 *   - These two identifier spaces MUST NEVER be conflated. Earlier versions of
 *     this file queried `StrategyDefinition` by `{ id: config.id, type: "COMPOSITE" }`
 *     which forced a non-UUID runtime ref into a UUID column. This file now
 *     exclusively uses `implementationRef` to look up persisted StrategyVersions
 *     and creates definitions on demand keyed by the implementationRef stored
 *     on the resulting version.
 */
import type { PrismaClient } from "@prisma/client";
import type { CombinationConfig } from "../../strategy/combination/CombinationConfig";
import { getCanonicalCompositeDisplayName } from "../../strategy/combination/CombinationConfig";
import { logger } from "../../../shared/logger/logger";

export interface StrategyVersionInfo {
  readonly strategyVersionId: string;
  readonly definitionId: string;
  readonly definitionType: "BASE" | "COMPOSITE";
}

export class StrategyVersionMapper {
  public constructor(
    private readonly prisma: PrismaClient,
    private readonly log: typeof logger = logger,
  ) {}

  /**
   * Resolve a BASE strategy's `implementationRef` to its current active
   * `StrategyVersion.id`.
   *
   * @param implementationRef  Matches `Strategy.id`, e.g. `"strategy.ma"`.
   * @param strategyName      Human-readable name for bootstrap.
   */
  public async resolveBaseStrategy(
    implementationRef: string,
    strategyName: string,
  ): Promise<StrategyVersionInfo> {
    // Look for an existing active version by implementationRef
    const existingVersion = await this.prisma.strategyVersion.findFirst({
      where: { implementationRef, isActive: true },
    });

    if (existingVersion) {
      const def = await this.prisma.strategyDefinition.findUnique({
        where: { id: existingVersion.definitionId },
      });
      return {
        strategyVersionId: existingVersion.id,
        definitionId: existingVersion.definitionId,
        definitionType: (def?.type ?? "BASE") as "BASE" | "COMPOSITE",
      };
    }

    // Bootstrap: create definition + version
    this.log.info({ implementationRef }, "search.StrategyVersionMapper.bootstrap");
    const newDef = await this.prisma.strategyDefinition.create({
      data: { type: "BASE", family: "TREND" },
    });

    const version = await this.prisma.strategyVersion.create({
      data: {
        definitionId: newDef.id,
        version: "1.0.0",
        name: strategyName,
        implementationRef,
        parameters: {},
        isActive: true,
      },
    });

    return {
      strategyVersionId: version.id,
      definitionId: newDef.id,
      definitionType: "BASE",
    };
  }

  /**
   * Resolve a COMPOSITE candidate's `CombinationConfig` to its
   * `StrategyVersion.id`.
   *
   * Identification model:
   *   - The composite's stable runtime identifier is `config.id`, which is
   *     a non-UUID string of the form `"strategy.composite.<slug>.<index>"`.
   *   - We look up an existing `StrategyVersion` by `implementationRef = config.id`.
   *   - If none exists, we create a `StrategyDefinition` (UUID id auto-generated
   *     by Prisma) and a `StrategyVersion` (UUID id auto-generated by Prisma)
   *     that records the stable implementationRef.
   *   - For each component we look up the underlying BASE strategy by its
   *     `implementationRef` and write a `CompositeComponent` row.
   *
   * @param config        The CombinationConfig from the CompositeCandidate.
   * @param strategyName  Human-readable name.
   */
  public async resolveCompositeStrategy(
    config: CombinationConfig,
    // Phase 3.4: `strategyName` is intentionally ignored — the
    // canonical display name is now derived from the actual
    // composite components and is therefore stable and
    // non-recursive. We keep the parameter name (no underscore) so
    // the public signature remains identical for existing callers
    // (HybridLoopGenerator, SearchService).
    _strategyName: string,
  ): Promise<StrategyVersionInfo> {
    if (!config.id || typeof config.id !== "string") {
      throw new Error("StrategyVersionMapper.resolveCompositeStrategy: config.id is required.");
    }

    // ── 1. Look up an existing active StrategyVersion by implementationRef ──
    const existingVersion = await this.prisma.strategyVersion.findFirst({
      where: { implementationRef: config.id, isActive: true },
      include: { definition: true },
    });

    if (existingVersion) {
      // Sync CompositeComponent rows for this version.
      await this.syncCompositeComponents(existingVersion.id, config.components);
      // Phase 3.4: derive the canonical display name from the
      // composite components (stable, non-recursive). We never write
      // a longer / recursive name on top of an existing one — that
      // was the source of names like
      //   "Bollinger + RSI → Bollinger + RSI → Bollinger + RSI".
      // The executable definition (components / weights / parameters /
      // operator / implementationRef) is unchanged by this update.
      const canonicalName = getCanonicalCompositeDisplayName(config);
      if (
        existingVersion.name !== canonicalName &&
        canonicalName.length < existingVersion.name.length
      ) {
        await this.prisma.strategyVersion.update({
          where: { id: existingVersion.id },
          data: { name: canonicalName },
        });
        this.log.info(
          {
            strategyVersionId: existingVersion.id,
            previousName: existingVersion.name,
            canonicalName,
          },
          "search.StrategyVersionMapper.canonicalNameRewritten",
        );
      }
      return {
        strategyVersionId: existingVersion.id,
        definitionId: existingVersion.definitionId,
        definitionType: existingVersion.definition.type,
      };
    }

    // ── 2. Bootstrap a fresh StrategyDefinition (COMPOSITE) + StrategyVersion ──
    // The definition's primary key is a UUID auto-generated by Prisma; the
    // version records `implementationRef = config.id` so we can look it up
    // next time by the same stable ref.
    this.log.info(
      { implementationRef: config.id },
      "search.StrategyVersionMapper.bootstrapComposite",
    );
    const newDef = await this.prisma.strategyDefinition.create({
      data: { type: "COMPOSITE", family: "TREND" },
    });

    // Phase 3.4: persist a canonical, non-recursive display name. The
    // generator-supplied `strategyName` may carry recursive parent
    // prefixes (e.g. "... → Bollinger + RSI → Bollinger + RSI"). We
    // derive the canonical name from the actual composite components
    // so the persisted label is stable across iterations and does not
    // accumulate parent prefixes.
    const canonicalBootstrapName = getCanonicalCompositeDisplayName(config);

    const version = await this.prisma.strategyVersion.create({
      data: {
        definitionId: newDef.id,
        version: "1.0.0",
        name: canonicalBootstrapName,
        implementationRef: config.id,
        parameters: {},
        isActive: true,
      },
    });

    await this.syncCompositeComponents(version.id, config.components);

    return {
      strategyVersionId: version.id,
      definitionId: newDef.id,
      definitionType: "COMPOSITE",
    };
  }

  /**
   * Replace the set of `CompositeComponent` rows for a given
   * `compositeVersionId`. Each row points at the underlying BASE strategy
   * version resolved by `implementationRef`.
   *
   * Runs inside a transaction so partial syncs are not visible.
   */
  private async syncCompositeComponents(
    compositeVersionId: string,
    components: CombinationConfig["components"],
  ): Promise<void> {
    await this.prisma.$transaction(async (tx) => {
      await tx.compositeComponent.deleteMany({ where: { compositeVersionId } });

      for (const component of components) {
        const componentVersion = await tx.strategyVersion.findFirst({
          where: { implementationRef: component.strategyId, isActive: true },
        });

        if (!componentVersion) {
          throw new Error(
            `StrategyVersionMapper: no active version found for implementationRef "${component.strategyId}"`,
          );
        }

        await tx.compositeComponent.upsert({
          where: {
            compositeVersionId_componentVersionId: {
              compositeVersionId,
              componentVersionId: componentVersion.id,
            },
          },
          update: {
            weight: component.weight,
            position: component.position,
          },
          create: {
            compositeVersionId,
            componentVersionId: componentVersion.id,
            weight: component.weight,
            position: component.position,
          },
        });
      }
    });
  }
}
